### ISSUE TITLE
rp2040 footprint cut out

### ISSUE THREAD

**Issue by michelepagot** [dlip/chouchou#2]
Hi @dlip, amazing work.

I'd like to use waveshare rp2040 zero in a board of mine and I'm searching for an Ergogen footprint for it.

I noticed yours is using a cut out to support flush soldering, I'm just not sure its ok for the waveshare module I have.

![image](https://github.com/user-attachments/assets/4e0a385e-c31c-483b-a0f7-66ab027156ff)

Here another board is using similar footprint: https://github.com/axhixh/mini-kbd/ : from the picture there seems that the MCU module is also mounted on pin headers and not soldered flush on the main board, so there looks like the hole is about heat dissipation.

**Comment by dlip** [comment]
@michelepagot I thought it was a hole for the cpu originally at first also, but it's actually for the reset buttons in case you want to design a reversible board. If you want to do it without headers, it will work if you add blobs of soldier to the pcb first, then place the mcu on top and join that up to the side of the castellated holes.
